#!/bin/bash

if ! command -v snap > /dev/null; then snap() { :; }; fi
if ! command -v flatpak > /dev/null; then flatpak() { :; }; fi

sudo /opt/McAfee/ens/tp/init/mfetpd-control.sh stop

sudo apt update
sudo apt install -y --fix-broken
sudo apt full-upgrade -y

sudo snap refresh

flatpak update -y
flatpak remove --unused -y
sudo flatpak repair

sudo /opt/McAfee/ens/tp/init/mfetpd-control.sh start

read -p "Press enter to continue"
